# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dfs.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tdfs.proto\x12\x08\x64\x61taNode\"4\n\x0b\x46ileRequest\x12\x11\n\tfile_name\x18\x01 \x01(\t\x12\x12\n\nblock_name\x18\x02 \x01(\t\"\"\n\x0c\x46ileResponse\x12\x12\n\nblock_data\x18\x01 \x01(\t\"L\n\x0f\x46ileInfoRequest\x12\x11\n\tfile_name\x18\x01 \x01(\t\x12\x12\n\nblock_name\x18\x02 \x01(\t\x12\x12\n\nblock_data\x18\x03 \x01(\t\"\"\n\x10\x46ileInfoResponse\x12\x0e\n\x06status\x18\x01 \x01(\t2\x89\x01\n\x06IOFile\x12\x38\n\x07GetFile\x12\x15.dataNode.FileRequest\x1a\x16.dataNode.FileResponse\x12\x45\n\x0cSendFileInfo\x12\x19.dataNode.FileInfoRequest\x1a\x1a.dataNode.FileInfoResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dfs_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_FILEREQUEST']._serialized_start=23
  _globals['_FILEREQUEST']._serialized_end=75
  _globals['_FILERESPONSE']._serialized_start=77
  _globals['_FILERESPONSE']._serialized_end=111
  _globals['_FILEINFOREQUEST']._serialized_start=113
  _globals['_FILEINFOREQUEST']._serialized_end=189
  _globals['_FILEINFORESPONSE']._serialized_start=191
  _globals['_FILEINFORESPONSE']._serialized_end=225
  _globals['_IOFILE']._serialized_start=228
  _globals['_IOFILE']._serialized_end=365
# @@protoc_insertion_point(module_scope)
